name: Main branch - Linux JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml -Dlwjgl.natives=natives-linux

#    - name: Copy to staging
#      run: mkdir staging && cp target/zatikon-*.jar staging

#    - name: Upload
#      uses: actions/upload-artifact@v4
#      with:
#        name: zatikon-1.2.0-dev-linux
#        path: target/zatikon-*.jar

    - name: Pack into tgz
      run: tar zcvf zatikon-1.2.0-dev-linux.tar.gz target/

    - name: Deploy Nightly
      uses: WebFreak001/deploy-nightly@v3.2.0
      with:
          upload_url: https://uploads.github.com/repos/zatikon/zatikon/releases/195528252/assets{?name,label}
          release_id: 195528252
          asset_path: ./zatikon-1.2.0-dev-linux.tar.gz
          asset_name: zatikon-1.2.0-dev-linux-$$.tar.gz
          asset_content_type: application/gzip

# Well it's cool it can be deployed but I don't need that now
#    - name: Publish package
#      run: mvn --batch-mode deploy
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# What I need is to create a release on Github and publish latest version on Flathub. TODO: that.
